temp/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Comments2__c</fullName>
        <description>Comments2 used in App as Additional info to be displayed</description>
        <inlineHelpText>Comments2</inlineHelpText>
        <label>Comments2</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <description>Comments to render in App</description>
        <inlineHelpText>Comments to render in App</inlineHelpText>
        <label>Comments</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
</CustomObject>

temp/objects/Inbox__c.object
<CustomObject>
    <description>Inbox</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account</description>
        <inlineHelpText>Account</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Inbox</relationshipLabel>
        <relationshipName>Inbox</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Fax_Number__c</fullName>
        <description>Fax Number</description>
        <inlineHelpText>Fax Number</inlineHelpText>
        <label>Fax Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status</description>
        <inlineHelpText>Status</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>eMail__c</fullName>
        <description>Signed document to be sent to</description>
        <label>eMail</label>
        <type>Email</type>
    </fields>
    <label>Inbox</label>
    <nameField>
        <displayFormat>D-{0000000}</displayFormat>
        <label>DocumentName</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inbox</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/Inbox_Synch_Tracker__c.object
<CustomObject>
    <description>Tracks last synch date by User</description>
    <fields>
        <fullName>Client_Synch_Date__c</fullName>
        <description>Date Time @ client when last synch completed</description>
        <label>Client Synch Date</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Synch_Date__c</fullName>
        <defaultValue>Now()</defaultValue>
        <description>Last Synch Date</description>
        <inlineHelpText>LastSynchDate</inlineHelpText>
        <label>Last Synch Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>User</description>
        <inlineHelpText>User</inlineHelpText>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Inbox_Synch_Tracker</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Inbox Synch Tracker</label>
    <nameField>
        <displayFormat>SYNC-{000000}</displayFormat>
        <label>SynchId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inbox Synch Tracker</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/SysParam__c.object
<CustomObject>
    <description>SysParam</description>
    <fields>
        <fullName>ParamType__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Param Type (true if used by client App)</description>
        <label>App Parameter</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>paramName__c</fullName>
        <description>param name</description>
        <label>paramName</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>paramValue__c</fullName>
        <description>param Value</description>
        <inlineHelpText>param Value</inlineHelpText>
        <label>paramValue</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>SysParam</label>
    <nameField>
        <displayFormat>PRM-{000000}</displayFormat>
        <label>SysParam Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SysParams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/classes/SC_eSignSvcs.cls
@RestResource(urlMapping='/eSign/*')
global with sharing class SC_eSignSvcs
{

@HttpPost
    global static void setSynchCompleteTimestamp(string strClientDateTime)
    {
       RestRequest req = RestContext.request;
       
       List<Inbox_Synch_Tracker__c> lST = new List< Inbox_Synch_Tracker__c>();
       lST = [Select id, user__c , Last_Synch_Date__c , Client_Synch_Date__c
                                             from Inbox_Synch_Tracker__c where user__c = :userinfo.getUserId() ];
        
       
        dateTime currentDateTime =system.now();
        if (lST.size()  == 0)
        {
          Inbox_Synch_Tracker__c  objSynchTrk = new Inbox_Synch_Tracker__c();
          objSynchTrk.user__c  = userinfo.getUserId();
          objSynchTrk.Last_Synch_Date__c = currentDateTime;
          objSynchTrk.Client_Synch_Date__c  = strClientDateTime ; 
          Insert objSynchTrk ;
        }
        else
        {
         Inbox_Synch_Tracker__c  objSynchTrk = lST[0];
         objSynchTrk.Last_Synch_Date__c = currentDateTime;
         objSynchTrk.Client_Synch_Date__c = strClientDateTime ; 
         Update objSynchTrk;
        }
        
    }

@HttpGet
    global static SC_WrapperUtility.supersobjectWrapper  getListOfAccounts()
    {
        String strAccountID = '' ;
        RestRequest req = RestContext.request;
         string strObject;
        if (Test.IsRunningTest())
         strObject = null;
        else{
          strObject = req.params.get('SYNCOBJECTNAME');
          strAccountID = req.params.get('ACCOUNTID');
          if (strAccountID == null || strAccountID == '') strAccountID = 'NA';
        }
        if (strObject == null )
        strObject = 'ALL' ;
        //List<SC_WrapperUtility.sobjectWrapper> lstWrapAccounts=new List<SC_WrapperUtility.sobjectWrapper>();
        List<SObject> lstWrapSysParams=new List<SObject >(); 
        List<SObject> lstWrapAccounts=new List<SObject >(); 
        List<SObject> lstWrapAttachments =new List<SObject >();  
        List<SObject> lstWrapInboxItems =new List<SObject >(); 
        String strComments = '';
        //List< SysParam__c > lP 
        
        if (strObject == 'ALL' || strObject  == 'SP'){
            lstWrapSysParams = [Select id, paramName__c, paramValue__c
                            from SysParam__c
                            Where ParamType__c = true
                            ];
        }
                            
        List<Account> lA;
        boolean bPersonAccountEnabled = SC_GlobalUtils.personAccountsEnabled() ;
        
        //if (bPersonAccountEnabled )
        {
            string strQuery = '';
            strQuery = 'Select id, isPersonAccount ,Name, PersonTitle, Salutation, firstname, lastname, recordType.name ,comments__c , comments2__c from Account';
            If (strAccountID != null && strAccountID != '' && strAccountID != 'NA'){
              strQuery = strQuery  + ' Where Id = \'' + strAccountID + '\'' ;
            }
            else{
               strQuery = strQuery  + ' Where Id in (Select account__c from Inbox__c ) Limit 10 ' ;
            }
            lA = Database.Query(strQuery);
        }
       /* else
        {
            lA = [Select id, Name,  Salutation, 
                                   firstname, lastname, recordType.name ,
                                   comments__c , comments2__c
                            from Account
                            Where Id in (Select account__c from Inbox__c )
                            //order by name
                            Limit 10
                            ];
        }*/
                                    
        
        //List<Inbox__c> lInboxItems
        if (strObject == 'ALL' || strObject  == 'INBOX'){
            if (strObject == 'INBOX' && strAccountID != 'NA'){
               lstWrapInboxItems = [SELECT id, Name , Account__r.name, Account__r.Id , status__c , Fax_Number__c , eMail__c 
                                      FROM Inbox__c where status__c = 'Pending'  
                                      and Account__c = : strAccountID
                                      ];
            }
            else{
            lstWrapInboxItems = [SELECT id, Name , Account__r.name, Account__r.Id , status__c , Fax_Number__c , eMail__c 
                                      FROM Inbox__c where status__c = 'Pending'  
                                      //and Account__r.isPersonAccount = true 
                                      ];
            }
        }
               
        //List<Attachment> lFiles 
        if (strObject == 'ALL' || strObject  == 'FILES'){
            lstWrapAttachments = [SELECT Id, ParentId, Name // , Body 
                                   from Attachment 
                                   where    parentid !=  null 
                                   and ParentId in ( Select id FROM Inbox__c where status__c = 'Pending'  
                                                      and Account__c in : lA )   //  and Account__r.isPersonAccount = true )
                                   and contenttype in ('application/pdf' )                   
                                   ];
        }
             
        /*
        for (SysParam__c obj  : lP )
        {
           SObject objWrapper = obj;
           lstWrapSysParams.add(objWrapper );
        }
        */
        if (strObject == 'ALL' || strObject  == 'ACCOUNT'){    
            if (bPersonAccountEnabled ){                       
            for (Account objAccount : lA)
            {
                  strComments = '';
                 /*  if ((objAccount.comments__c == null || objAccount.comments__c == '') && objAccount.isPersonAccount) 
                   {
                           strComments = objAccount.Salutation + ' ' +  objAccount.firstName + ' ' + objAccount.LastName + ' ' ;
                           objAccount.comments__c =     strComments;
                   }*/
                   if ((objAccount.comments__c == null || objAccount.comments__c == ''))// && !objAccount.isPersonAccount) 
                   {
                       strComments = objAccount.Name  ;
                       objAccount.comments__c = strComments;
                   }
                   if (objAccount.comments2__c == null || objAccount.comments2__c == '') 
                   {
                       
                       objAccount.comments2__c = 'No Info available';
                   }
                   //SObject objWrapper = objAccount;
                   lstWrapAccounts.add(objAccount);
            } // for
            } //if (bPersonAccountEnabled )
            else {
            for (Account objAccount : lA)
            {
                  strComments = '';
                   if ((objAccount.comments__c == null || objAccount.comments__c == '')) 
                   {
                       strComments = objAccount.Name  ;
                       objAccount.comments__c = strComments;
                   }
                   if (objAccount.comments2__c == null || objAccount.comments2__c == '') 
                   {
                       
                       objAccount.comments2__c = 'No Info available';
                   }
                   //SObject objWrapper = objAccount;
                   lstWrapAccounts.add(objAccount);
            } // for
            } //if  bPersonAccountEnabled   == false
                        
        } // if all or account
        System.debug('lstWrapAccounts.size ' + lstWrapAccounts.size());
        // System.debug('lstWrapAccounts.size ' + lstWrapAccounts );
        /*
        for (Inbox__c objInbox : lInboxItems)
        {
           SObject objWrapper = objInbox;
           lstWrapInboxItems.add(objWrapper );
        }
        
        for (Attachment objFile : lFiles)
        {
           // SC_WrapperUtility.sobjectWrapper wrapper=new SC_WrapperUtility.sobjectWrapper(objAccount);
           SObject objWrapper = objFile;
           lstWrapAttachments.add(objWrapper );
        }
        */
        dateTime newDate=system.now();
        String dateInFormat = newDate.formatGMT('yyyy-MM-dd HH:mm:ss');
        
        SC_WrapperUtility.supersobjectWrapper superWrap=new SC_WrapperUtility.supersobjectWrapper();//Instantiating the superclass
    
        if (strObject == 'ALL' || strObject  == 'SP'){
            superWrap.SysParams = lstWrapSysParams ;
        }
        
        if (strObject == 'ALL' || strObject  == 'ACCOUNT'){
            superWrap.Accounts = lstWrapAccounts; 
        }
        
        if (strObject == 'ALL' || strObject  == 'INBOX'){
            superWrap.InboxItems = lstWrapInboxItems; 
        }
        
        if (strObject == 'ALL' || strObject  == 'FILES'){
            superWrap.Attachments = lstWrapAttachments; 
        }
        
        superWrap.SyncTimestamp=dateInFormat;//Current UTC timestamp of the server  
        superWrap.message     = 'Success';
        superWrap.errorCode = '0' ;              
        system.debug('superWrap ' + superWrap );
        return superWrap ;
    
    } // getListOfAccounts

}