temp/objects/SC_Error_Log__c.object
<CustomObject>
    <description>Object to record Error logs</description>
    <fields>
        <fullName>Message__c</fullName>
        <description>Message</description>
        <inlineHelpText>Message</inlineHelpText>
        <label>Message</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <description>Object related to error</description>
        <inlineHelpText>Object</inlineHelpText>
        <label>Object</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Default</fullName>
                </value>
                <value>
                    <fullName>Account</fullName>
                </value>
                <value>
                    <fullName>Contact</fullName>
                </value>
                <value>
                    <fullName>Case</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RecordDate__c</fullName>
        <defaultValue>Now()</defaultValue>
        <description>Date-Time when error occurred</description>
        <inlineHelpText>Date-Time when error occurred</inlineHelpText>
        <label>RecordDate</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>RecordId__c</fullName>
        <description>ID of record related to error</description>
        <label>RecordId</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <description>Apex Code / Process /  System that caused this error</description>
        <inlineHelpText>Apex Code / Process /  System that caused this error</inlineHelpText>
        <label>Source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ERROR</fullName>
                </value>
                <value>
                    <fullName>INFO</fullName>
                </value>
                <value>
                    <fullName>SUCCESS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Application Error Log</label>
    <nameField>
        <displayFormat>EL-{000000}</displayFormat>
        <label>SC_Error_Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Error Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SC_GlobalUtils.cls
public without sharing class SC_GlobalUtils {

    // Created By : 
    // class Application_Exception 
    //
    public without sharing class Application_Exception extends Exception{
    
    } // re-usable class to handle logging of exceptions


    public static Boolean nullOrEmpty(Object o) {
      return (null == o) ||
        ((o instanceof String) && (0 == ((String)o).trim().length())) ||
        ((o instanceof List<object>) && (0 == ((List<object>)o).size()));
    }
    
    
    // Created By : 
    // checkNull 
    //
    public static String checkNull(String s){
       system.debug('String sent in: '+s);
       return s==null?'':s;  
    } // Check If Input is null
    
    public static string genGUID()    
    {
        Blob b = Crypto.GenerateAESKey(128);
        String h = EncodingUtil.ConvertTohex(b);
        String guid = h.SubString(0,8)+ '-' + h.SubString(8,12) + '-' + h.SubString(12,16) + '-' + h.SubString(16,20) + '-' + h.substring(20);
        system.debug(guid);
        return guid ;
    } //genGUID
    
    // Created By : 
    // CreateErrorLog
    //   
    public static SC_Error_Log__c  CreateErrorLog(string Type,string Message, string Source,string objName,String recId){
      system.debug('Start of UpdateApplicationLog method');
      system.debug('Parameters passed:-');
      system.debug('Source='+Source);
      system.debug('objName='+objName);
      system.debug('Type='+Type);
      system.debug('Message='+Message);
      
      datetime nowDateTime = datetime.now();
      
      SC_Error_Log__c applog = new SC_Error_Log__c();
      applog.RecordDate__c = nowDateTime;
      applog.Type__c       =     Type;
      applog.Message__c    =     Message;
      applog.Source__c     =     Source;
      applog.Object__c     =     objName;
      applog.RecordId__c   =    recId;
      return applog;
   } // CreateErrorLog
   
   public static Boolean personAccountsEnabled()
{
    // Describe the Account object to get a map of all fields
    // then check to see if the map contains the field 'isPersonAccount'
    return Schema.sObjectType.Account.fields.getMap().containsKey( 'isPersonAccount' );
}
   
   

} // class